### ISSUE TITLE
Wrong bitwidth when using N bit NOT

### ISSUE THREAD

**Issue by petraratkai** [tomcl/issie#283]
**Describe the bug**
When connecting an output port to an N bit NOT component, the values displayed have more bits than the output port.

**To Reproduce**
1. Create a 5 bit input port, a 5 bit NOT gate, 5 bit output port
2. Simulate

**Expected behavior**
Display value with the expected width

**Screenshots**
![image](https://github.com/tomcl/issie/assets/60006935/6f9cba55-2209-4770-810f-47d0b60e520d)

**Comment by petraratkai** [comment]
The following circuit also produces an error:
![image](https://github.com/tomcl/issie/assets/60006935/6d3754a1-2b4c-4897-9386-2f8e226a894a)
C1 is 1, the output of the inverter should be 0, compared to 0 should output 1 but Issie outputs 0.

**Comment by lucasng32** [comment]
Could I be assigned to this?

**Comment by tomcl** [comment]
Done.

**Comment by lucasng32** [comment]
The bug still exists on the new simulator
A bigint version of NOT exists for NOT on busses > 32 bits: 
```
| NbitsNot numberOfBits, true ->
        let a = insBigInt 0
        // failwithf $"TODO: fable does not support op_OnesComplement function"
        // BigWord (System.Numerics.BigInteger.op_OnesComplement a)  FIX: 2^n-1-a
        let w = comp.InputWidth 0
        // (bigint^w)
        let (minusOne: bigint) = ((bigint 2) <<< w) - (bigint 1)
        let res = minusOne - a
        putBigInt 0 res
```
I implemented NOT for <= 32 bits similarly. I noticed the bitshift seemed to be circular so I added a case for 32 bits: 
```
| NbitsNot numberOfBits, false ->
        let a = insUInt32 0
        let w = comp.InputWidth 0
        let minusOne = (1u <<< w) - 1u
        let res = 
            match w with 
            | 32 -> minusOne - a - 1u
            | _ -> minusOne - a
        putUInt32 0 res
```
It's also my first time contributing, I've read through the wiki and wanted to clarify some things: 
I've created a fork of master, created a new branch, applied the changes and then commit. 
I then pushed the branch to my fork. 
Is the next step to open a pull request to this repository's master branch?

**Comment by tomcl** [comment]
Assuming that you have rebased on master (and dealt with any conflicts due to its change, if it has changed) yes,

**Comment by tomcl** [comment]
closed by #342
